language: ruby
rvm:
  - 2.1.0
env:
  - DB=sqlite
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rspec spec
before_script:
  - psql -c 'create database notes_test' -U postgres
