# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf60d604ea1bd732f0a760dc999ff360d083d4e72f23c165def7c732899fcffb57f0677cd2f069d0d957290d065a300068759f833e7dd96e92eb00dec91d6bb7

test:
  secret_key_base: 93d96f98527debf1304bf17649c904f8167a128db87eab997458d4872d213677860ef043bff0f541931c3d297d2d234734ad063be066ee40c434538892101a36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
